// <auto-generated />
using System;
using APDS7311_POE_PART2_ST10076452.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APDS7311_POE_PART2_ST10076452.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250604200920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APDS7311_POE_PART2_ST10076452.Server.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 4, 20, 9, 19, 538, DateTimeKind.Utc).AddTicks(6546),
                            Email = "khumalo.slindelo@bank.com",
                            EmployeeNumber = "EMP001",
                            FullName = "Slindelo Khumalo",
                            Password = "46e190379edbde8dec03a1d98f5c9443754bed3c",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("APDS7311_POE_PART2_ST10076452.Server.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("accNumber");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("APDS7311_POE_PART2_ST10076452.Server.Models.PaymentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("accNumber");

                    b.ToTable("PaymentRequests");
                });

            modelBuilder.Entity("APDS7311_POE_PART2_ST10076452.Server.Models.Users", b =>
                {
                    b.Property<string>("accNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("idNumber")
                        .HasColumnType("int");

                    b.HasKey("accNumber");

                    b.HasIndex("accNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("APDS7311_POE_PART2_ST10076452.Server.Models.Login", b =>
                {
                    b.HasOne("APDS7311_POE_PART2_ST10076452.Server.Models.Users", "Users")
                        .WithMany("Logins")
                        .HasForeignKey("accNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("APDS7311_POE_PART2_ST10076452.Server.Models.PaymentRequest", b =>
                {
                    b.HasOne("APDS7311_POE_PART2_ST10076452.Server.Models.Users", "User")
                        .WithMany("PaymentRequests")
                        .HasForeignKey("accNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APDS7311_POE_PART2_ST10076452.Server.Models.Users", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("PaymentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
