version: 2.1

executors:
  dotnet_executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    working_directory: ~/repo

jobs:
  build-and-scan:
    executor: dotnet_executor
    steps:
      - checkout

      - run:
          name: Install Node.js for React build
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs

      - run:
          name: Install SonarScanner for .NET
          command: |
            dotnet tool install --global dotnet-sonarscanner
            echo 'export PATH="$PATH:/root/.dotnet/tools"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Restore NuGet packages
          command: dotnet restore

      - run:
          name: Begin SonarQube analysis
          command: |
            dotnet-sonarscanner begin \
              /k:"MveloK_APDS_POE_PART_2" \
              /d:sonar.host.url="http://localhost:3000" \
              /d:sonar.login="e15c2cfc14acc4ea9d2a17b589962c336c1c22eb"

      - run:
          name: Build the .NET project
          command: dotnet build --no-incremental

      - run:
          name: End SonarQube analysis
          command: |
            dotnet-sonarscanner end /d:sonar.login="e15c2cfc14acc4ea9d2a17b589962c336c1c22eb"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build-and-scan
